//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSDT.CustomRules.Tests.SaveTranMastHavePairRollbackTranTestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSDT.CustomRules.Tests.SaveTranMastHavePairRollbackTranTestData.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [Northwind].[SaveTransactionSampleProcedure]
        ///as
        ///begin
        ///	set nocount on
        ///	declare @trancount int = @@trancount
        ///
        ///	begin try
        ///		if @trancount = 0
        ///			begin tran
        ///		else
        ///			save tran SaveTransactionSampleProcedure
        ///
        ///		---
        ///		-- Some code
        ///		---
        ///		
        ///		commit tran
        ///	end try
        ///	begin catch
        ///		declare @xActState int = xact_state()
        ///		declare @errorNumber int = error_number()
        ///		declare @errorMessage nvarchar(max) = error_message()
        ///
        ///		if (@xActState = -1) or (@xActState = 1 and @trancount =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaveTransactionSampleProcedureBalanced {
            get {
                return ResourceManager.GetString("SaveTransactionSampleProcedureBalanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [Northwind].[SaveTransactionSampleProcedure]
        ///as
        ///begin
        ///	set nocount on
        ///	declare @trancount int = @@trancount
        ///
        ///	begin try
        ///		if @trancount = 0
        ///			begin tran
        ///		else
        ///			save tran SaveTransactionSampleProcedure
        ///
        ///		---
        ///		-- Some code
        ///		---
        ///		
        ///		commit tran
        ///	end try
        ///	begin catch
        ///		declare @xActState int = xact_state()
        ///		declare @errorNumber int = error_number()
        ///		declare @errorMessage nvarchar(max) = error_message()
        ///
        ///		if (@xActState = -1) or (@xActState = 1 and @trancount =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaveTransactionSampleProcedureNotBalanced {
            get {
                return ResourceManager.GetString("SaveTransactionSampleProcedureNotBalanced", resourceCulture);
            }
        }
    }
}
